development:
  adapter: postgresql
  encoding: utf-8
  database: grape_api_development
  pool: 5
  username: root
  password: root
  host: localhost
  port: 5432

test: &test
  adapter: postgresql
  encoding: utf-8
  database: grape_api_test
  pool: 5
  username: root
  password: root
  host: localhost
  port: 5432
